# GitHub Pages Jekyll Configuration - LAA Unterrichtsmaterialien
# Optimiert für Volleyball BUV mit iPad-Integration

# Site Settings
title: "LAA Unterrichtsmaterialien"
description: "Innovative Unterrichtsmaterialien für die LAA-Ausbildung mit iPad-Integration, systemtheoretischen Ansätzen und PATA-Standards"
baseurl: ""
url: "https://paulad.github.io"
author: "Paul Cebulla"
email: "paul.cebulla@laa-system.de"

# Repository Information
repository: "paulad/snflsknfkldnfs.github.io"
github_username: paulad

# Language and Locale
lang: de
locale: de_DE
timezone: Europe/Berlin

# Build Settings
markdown: kramdown
highlighter: rouge
permalink: pretty

# GitHub Pages compatible plugins only
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# SEO and Social
seo_tag:
  title_template: "%s | LAA Unterrichtsmaterialien"

# Default Front Matter
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
      author: "Paul Cebulla"
  - scope:
      path: "unterricht/Sport"
    values:
      layout: "default"
      category: "sport"
      subject: "Sport"
  - scope:
      path: "unterricht/GPG"
    values:
      layout: "default"
      category: "gpg"
      subject: "GPG"

# Collections (optional, for future expansion)
collections:
  sport:
    output: true
    permalink: /:collection/:name/
  buv:
    output: true
    permalink: /:collection/:name/

# Kramdown Settings
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'codehilite'

# Exclude from processing (GitHub Pages compatible)
exclude:
  - .git
  - .github
  - node_modules
  - "package*.json"
  - README.md
  - LICENSE
  - "Gemfile*"
  - vendor
  - .DS_Store
  - logs
  - "mcp-*"
  - development
  - meta
  - _transitions
  - chat_transitions
  - ".env*"
  - "*.pid"
  - "*.log"
  - "*.disabled"

# Include files that start with underscore
include:
  - _redirects
  - _headers

# Sass Settings
sass:
  sass_dir: _sass
  style: compressed

# Custom Variables for Site
volleyball_buv:
  title: "Volleyball BUV - UE3: Unteres Zuspiel"
  status: "completed"
  date: "2025-07-09"
  seminar: "SW V"
  class: "8ab"
  students: 16
  stations: 6

featured_materials:
  - name: "Volleyball BUV"
    description: "6-Stationen-System mit iPad-Integration"
    url: "/unterricht/Sport/Sm8ab/Sm8ab_LB4_4_Volleyball/volleyball-ue3-buv.html"
    status: "live"
    innovation: "iPad-HTML-Stationskarten"
  - name: "GPG Arbeitsweisen"
    description: "Systemtheoretische Politikdidaktik"
    url: "/unterricht/GPG_Arbeitsweisen_LAA_Training/"
    status: "available"

# Navigation Structure
navigation:
  - title: "Sport"
    url: "/unterricht/Sport/"
    icon: "🏃‍♂️"
    featured: true
  - title: "GPG"
    url: "/unterricht/GPG_Arbeitsweisen_LAA_Training/"
    icon: "🏛️"
    featured: true
  - title: "Tools"
    url: "/qr-generator.html"
    icon: "🛠️"

# GitHub Pages specific settings
github_pages:
  environment: "production"
  branch: "main"

# Manifest for PWA
manifest:
  name: "LAA Unterrichtsmaterialien"
  short_name: "LAA Materials"
  description: "Innovative Unterrichtsmaterialien mit iPad-Integration"
  start_url: "/"
  display: "standalone"
  theme_color: "#2c5282"
  background_color: "#ffffff"

# Performance and SEO
future: false
show_drafts: false
limit_posts: 10
